import { Project } from '@/types/projects'

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'mock-1',
    name: 'Kvadraturen Kvartal',
    location: 'Kristiansand',
    address: 'Markens gate 14, 4611 Kristiansand',
    coordinates: [58.1471, 7.9963],
    status: 'prosjektering',
    bra_m2: 7800,
    units: 68,
    floors: 8,
    zoning_status: 'Offentlig ettersyn',
    zoning_code: 'KRS-2201',
    description: 'Transformasjon av eldre kontorbygg i Kvadraturen til moderne leiligheter med næring i 1. etasje. Bevarer fasadens historiske preg.',
    completion_year: 2027,
    investment_mnok: 228,
    analysis: {
      sol:           { score: 76, label: 'Solforhold',   description: 'Gode solforhold mot sør og vest. Noe skyggelegging fra nabobygg om morgenen.' },
      støy:          { score: 52, label: 'Støy',         description: 'Trafikkstøy fra Markens gate krever tiltak mot gateplan.' },
      flom:          { score: 88, label: 'Flomrisiko',   description: 'Lavt flomrisikoområde, lite eksponert mot bekker og vassdrag.' },
      fjernvirkning: { score: 81, label: 'Fjernvirkning', description: 'Positiv fjernvirkning. Tilpasser seg Kvadraturens rutenett godt.' },
    },
  },
  {
    id: 'mock-2',
    name: 'Havnefront Vest',
    location: 'Kristiansand',
    address: 'Vestre Strandgate 38, 4611 Kristiansand',
    coordinates: [58.1448, 7.9872],
    status: 'regulering',
    bra_m2: 14200,
    units: 124,
    floors: 10,
    zoning_status: 'Reguleringsplan',
    zoning_code: 'KRS-1987',
    description: 'Utvikling av tidligere havnearealer til bolig og næring med sjøfrontkvaliteter. Unikt bygg langs Otra-munningen med panoramautsikt.',
    completion_year: 2028,
    investment_mnok: 415,
    analysis: {
      sol:           { score: 93, label: 'Solforhold',   description: 'Eksepsjonelle solforhold mot sør. Lite skyggeproblematikk.' },
      støy:          { score: 44, label: 'Støy',         description: 'Havneaktivitet og fergetrafikk gir merkbar bakgrunnsstøy. Fasadetiltak nødvendig.' },
      flom:          { score: 58, label: 'Flomrisiko',   description: 'Moderat risiko ved stormflo. Sokkeletasje heves 1,2 m over normalnivå.' },
      fjernvirkning: { score: 90, label: 'Fjernvirkning', description: 'Ikonisk sjøfrontprofil. Positiv bidrag til Kristiansands bysilhuett.' },
    },
  },
  {
    id: 'mock-3',
    name: 'Lund Terrasse',
    location: 'Kristiansand',
    address: 'Lundsiden 8, 4616 Kristiansand',
    coordinates: [58.1558, 7.9891],
    status: 'salg',
    bra_m2: 4600,
    units: 42,
    floors: 5,
    zoning_status: 'Vedtatt',
    zoning_code: 'KRS-1754',
    description: 'Attraktivt boligprosjekt på Lund med sol fra morgen til kveld. Gangavstand til sentrum og Baneheia. Ferdigstilt 2025.',
    completion_year: 2025,
    investment_mnok: 138,
    analysis: {
      sol:           { score: 88, label: 'Solforhold',   description: 'Svært gode solforhold. Terrasse mot sør/sørvest.' },
      støy:          { score: 78, label: 'Støy',         description: 'Rolig boliggate. Minimal trafikkpåvirkning.' },
      flom:          { score: 95, label: 'Flomrisiko',   description: 'Høytliggende tomt, ingen flomrisiko.' },
      fjernvirkning: { score: 74, label: 'Fjernvirkning', description: 'Tilpasser seg Lunds kvartalsstruktur godt.' },
    },
  },
  {
    id: 'mock-4',
    name: 'Slettheia Boligpark',
    location: 'Kristiansand',
    address: 'Slettaveien 42, 4626 Kristiansand',
    coordinates: [58.1672, 8.0214],
    status: 'mulighetsstudie',
    bra_m2: 9200,
    units: 88,
    floors: 4,
    zoning_status: 'Reguleringsplan',
    zoning_code: 'KRS-2389',
    description: 'Familievennlig boligutbygging på Slettheia med nærhet til skoler og Otra for friluftsliv. Lav bebyggelse tilpasset eksisterende nabolag.',
    completion_year: 2029,
    investment_mnok: 264,
    analysis: {
      sol:           { score: 82, label: 'Solforhold',   description: 'Åpent terreng gir gode solforhold gjennom hele dagen.' },
      støy:          { score: 71, label: 'Støy',         description: 'Rolig område. Noe støy fra Vågsbygdveien krever skjerming nordside.' },
      flom:          { score: 84, label: 'Flomrisiko',   description: 'Høyereliggende enn Otra-flaten. Lav risiko.' },
      fjernvirkning: { score: 65, label: 'Fjernvirkning', description: 'Lavblokker tilpasser seg kuppert terreng.' },
    },
  },
  {
    id: 'mock-5',
    name: 'Lillesand Brygge',
    location: 'Lillesand',
    address: 'Strandpromenaden 5, 4790 Lillesand',
    coordinates: [58.2492, 8.3771],
    status: 'mulighetsstudie',
    bra_m2: 3100,
    units: 28,
    floors: 4,
    zoning_status: 'Reguleringsplan',
    zoning_code: 'LIL-0441',
    description: 'Eksklusivt sjøfrontprosjekt i Lillesand sentrum. Bryggepromenade i 1. etasje, leiligheter med sjøutsikt i øvrige etasjer.',
    completion_year: 2029,
    investment_mnok: 98,
    analysis: {
      sol:           { score: 91, label: 'Solforhold',   description: 'Sørvendt mot Lillesandsfjorden. Ypperlige solforhold.' },
      støy:          { score: 66, label: 'Støy',         description: 'Båttrafikk i sommermånedene. Rolig resten av året.' },
      flom:          { score: 55, label: 'Flomrisiko',   description: 'Stormflo fra fjorden er en relevant faktor. Sikres med hevet sokkeletasje.' },
      fjernvirkning: { score: 86, label: 'Fjernvirkning', description: 'Styrker Lillesands identitet som kystby.' },
    },
  },
  {
    id: 'mock-6',
    name: 'Arendal Kvartal',
    location: 'Arendal',
    address: 'Tyholmveien 3, 4836 Arendal',
    coordinates: [58.4614, 8.7726],
    status: 'prosjektering',
    bra_m2: 10400,
    units: 94,
    floors: 7,
    zoning_status: 'Sluttbehandling',
    zoning_code: 'ARE-1102',
    description: 'Sentrumsnær utvikling i Arendal med utsikt over Nidelva og skjærgården. Blanding av boliger, kontorer og servering.',
    completion_year: 2027,
    investment_mnok: 312,
    analysis: {
      sol:           { score: 79, label: 'Solforhold',   description: 'Gode solforhold med unntak av noe skygging fra eksisterende bygg mot nord.' },
      støy:          { score: 68, label: 'Støy',         description: 'Sentrumsgate med moderat trafikk. Tilfredsstillende med fasadetiltak.' },
      flom:          { score: 72, label: 'Flomrisiko',   description: 'Nidelva i nærheten. Middels risiko ved 200-årsflom.' },
      fjernvirkning: { score: 83, label: 'Fjernvirkning', description: 'Markant bygg som forsterker Arendals sentrumsidentitet.' },
    },
  },
  {
    id: 'mock-7',
    name: 'Grimstad Campus',
    location: 'Grimstad',
    address: 'Jon Lilletuns vei 7, 4879 Grimstad',
    coordinates: [58.3398, 8.5932],
    status: 'regulering',
    bra_m2: 6200,
    units: 58,
    floors: 5,
    zoning_status: 'Offentlig ettersyn',
    zoning_code: 'GRI-0778',
    description: 'Studentboliger og næringsarealer tilknyttet UiA Grimstad. Tilpasset behovet for rimelige leieboliger i universitetsbyen.',
    completion_year: 2028,
    investment_mnok: 174,
    analysis: {
      sol:           { score: 74, label: 'Solforhold',   description: 'Akseptable solforhold. Noe skygging fra universitetsbygget mot vest.' },
      støy:          { score: 80, label: 'Støy',         description: 'Rolig campusområde. God støysituasjon.' },
      flom:          { score: 90, label: 'Flomrisiko',   description: 'Høytliggende tomt, minimal flomrisiko.' },
      fjernvirkning: { score: 69, label: 'Fjernvirkning', description: 'Funksjonell profil tilpasset campusmiljøet.' },
    },
  },
]
